apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-niginx
  labels:
    app: web-niginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-niginx
  template:
    metadata:
      labels:
        app: web-niginx
        version: "0.1"
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: web-niginx
        image: "{{IMAGE_NAME}}"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 5
          periodSeconds: 5